# Generated by Django 4.0.1 on 2022-01-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditInfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_creditcards', models.IntegerField()),
                ('annual_gross_salary', models.IntegerField()),
                ('overdueaccounts', models.IntegerField()),
                ('total_credit_balances', models.IntegerField()),
                ('new_credit_cards', models.IntegerField()),
                ('first_creditloan', models.IntegerField()),
                ('total_credit_limit', models.IntegerField()),
                ('bankruptcy', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentInfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('contract', models.CharField(max_length=80)),
                ('years_at_employment', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=10)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
