# Generated by Django 4.0.1 on 2022-01-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinCred', '0002_remove_employmentinfor_id_creditinfor_employment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='created_at',
        ),
    ]
