# Generated by Django 4.0.1 on 2022-01-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinCred', '0003_remove_personaldetails_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditinfor',
            name='employment',
        ),
        migrations.RemoveField(
            model_name='employmentinfor',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='employmentinfor',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
