# Generated by Django 4.0.1 on 2022-01-26 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinCred', '0004_remove_creditinfor_employment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentinfor',
            name='id',
        ),
        migrations.AddField(
            model_name='creditinfor',
            name='employment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FinCred.employmentinfor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employmentinfor',
            name='person',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='FinCred.personaldetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='phone_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
