# Generated by Django 4.0.1 on 2022-01-26 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinCred', '0005_remove_employmentinfor_id_creditinfor_employment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentinfor',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employmentinfor',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FinCred.personaldetails'),
        ),
    ]
