# Generated by Django 4.0.1 on 2022-01-26 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinCred', '0006_employmentinfor_id_alter_employmentinfor_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditinfor',
            name='employment',
        ),
        migrations.RemoveField(
            model_name='creditinfor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employmentinfor',
            name='id',
        ),
        migrations.AddField(
            model_name='creditinfor',
            name='person2',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='FinCred.employmentinfor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employmentinfor',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='FinCred.personaldetails'),
        ),
    ]
