# Generated by Django 4.0.1 on 2022-01-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinCred', '0008_remove_creditinfor_person2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditinfor',
            name='employment',
        ),
    ]
