# Generated by Django 4.0.1 on 2022-01-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinCred', '0010_creditinfor_employment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditinfor',
            name='employment',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, to='FinCred.employmentinfor'),
        ),
    ]
