# Generated by Django 4.0.1 on 2022-01-27 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinCred', '0011_alter_creditinfor_employment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentinfor',
            name='person',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='FinCred.personaldetails'),
        ),
    ]
