# Generated by Django 4.0.1 on 2022-01-27 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinCred', '0012_employmentinfor_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditinfor',
            name='employment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinCred.employmentinfor'),
        ),
        migrations.AlterField(
            model_name='employmentinfor',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinCred.personaldetails'),
        ),
    ]
