# Generated by Django 4.0.1 on 2022-01-27 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinCred', '0013_alter_creditinfor_employment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditinfor',
            name='employment',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, to='FinCred.employmentinfor'),
        ),
        migrations.AlterField(
            model_name='employmentinfor',
            name='person',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='FinCred.personaldetails'),
        ),
    ]
